---
apiVersion: mykubeapp/v1
kind: Deployment
metadata:
 name: mykubeapp
 labels:
  app: mykubeapp
spec:
 replicas: 2
 selector:
  matchLabels:
   app: mykubeapp
 template:
  metadata: 
   labels:
    app: mykubeapp
  spec:
   containers:
   - name: mykubeapp
     image: sourabhrana46/k8s:tagversion
     ports:
     - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: mykubeapp
spec:
  type: LoadBalancer
  selector:
    app: mykubeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
